In [124]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3])

In [4]:
arr

array([1, 2, 3])

In [14]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.random.rand(3,2)

array([[0.91601714, 0.24835279],
       [0.34813688, 0.16653544],
       [0.36514275, 0.78554417]])

In [27]:
np.random.randn(3,2)

array([[ 0.15764201,  0.31008635],
       [-0.36476208,  0.28141083],
       [-0.12934443, -0.15454558]])

In [44]:
arr=np.array([[1,2,3],[4,5,6]])

In [35]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
print(arr.shape)

(2, 3)


In [38]:
print(arr.ndim)

2


In [41]:
print(arr.size)

6


In [45]:
print(arr.dtype)

int64


In [53]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [48]:
a+b

array([5, 7, 9])

In [51]:
a*b

array([ 4, 10, 18])

In [54]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [59]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [57]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [60]:
A@B

array([[19, 22],
       [43, 50]])

In [74]:
arr=np.array([1,2,3,4])

In [63]:
arr.sum()

np.int64(10)

In [66]:
arr.mean()

np.float64(2.5)

In [69]:
arr.max()

np.int64(4)

In [72]:
arr.min()

np.int64(1)

In [75]:
arr.std()

np.float64(1.118033988749895)

In [84]:
arr=np.array([1,2,3,4,5])

In [79]:
arr[0]

np.int64(1)

In [82]:
arr[1:4]

array([2, 3, 4])

In [85]:
arr[::2]

array([1, 3, 5])

In [96]:
arr=np.array([[1,2,3],[4,5,6]])

In [88]:
arr[0,1]

np.int64(2)

In [91]:
arr[0,1]

np.int64(2)

In [94]:
arr[:,1]

array([2, 5])

In [97]:
arr[1, :2]

array([4, 5])

In [99]:
arr=np.array([1,2,3,4,5])

In [100]:
mask=arr>3

In [101]:
arr[mask]

array([4, 5])

In [109]:
arr=np.arange(6)

In [107]:
arr

array([0, 1, 2, 3, 4, 5])

In [104]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [110]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [119]:
a=np.array([1,2])
b=np.array([3,4])

In [113]:
np.concatenate

<function concatenate at 0x0000018B04CFEEF0>

In [114]:
import numpy as np
a=np.array([1,2])
b=np.array([3,4])
np.concatenate((a,b))

array([1, 2, 3, 4])

In [117]:
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [120]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [122]:
a=np.array([1,2,3])

In [123]:
a+5 # [6,7,8]

array([6, 7, 8])

In [125]:
np.save('array.npy',arr)

In [126]:
loaded_arr=np.load('array.npy')